<MainScreen>
    BoxLayout:
        orientation: 'vertical'
        Label:
            text: 'top'
            size_hint: 1, .1
            spacing: 5
            font_size: 30
        GridLayout:
            cols: 4
            Button:
                text: 'Add Button'
            Button:
                text: 'Remove Button'
            Button:
                text: 'Shit'
            Button:
                text: '1'
            Button:
                text: '2'
